/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Rectangle with x, y, width, height. */
export interface Rect {
  x: number
  y: number
  width: number
  height: number
}
export interface DisplaySource {
  kind: string
  monitorHandle: bigint
  /** Numeric display index matching Electron's desktopCapturer display_id. */
  displayId: string
  /** Human-readable name (monitor model or "Display N (WxH)"). */
  name: string
  primary: boolean
  bounds: Rect
}
export interface WindowSource {
  kind: string
  hwnd: bigint
  title: string
  pid: number
  /** Executable filename (e.g. "discord.exe"). */
  processName: string
  bounds: Rect
}
export interface Capabilities {
  wgc: boolean
  wgcBorderOptional: boolean
  processLoopback: boolean
  windowsBuild: number
}
export declare function listDisplays(): Array<DisplaySource>
export declare function listWindows(): Array<WindowSource>
export declare function getCapabilities(): Capabilities
export interface CaptureOptionsJs {
  source: SourceSpec
  delivery?: DeliverySpec
  fps?: number
  includeCursor?: boolean
  borderRequired?: boolean
}
export interface SourceSpec {
  kind: string
  monitorHandle?: bigint
  hwnd?: bigint
}
export interface DeliverySpec {
  type: string
  codec?: string
  bitrateBps?: number
  fps?: number
  keyframeIntervalMs?: number
  hdr10?: boolean
  ltrCount?: number
  intraRefresh?: boolean
  intraRefreshPeriod?: number
  roiEnabled?: boolean
}
export interface CaptureStatsJs {
  deliveredFrames: bigint
  droppedFrames: bigint
  encodedUnits: bigint
}
export interface AudioOptionsJs {
  mode: string
  pid?: number
  includeTree?: boolean
}
export interface AudioStatsJs {
  deliveredChunks: bigint
  droppedChunks: bigint
  discontinuities: bigint
}
export declare function version(): string
export declare class CaptureSession {
  constructor(opts: CaptureOptionsJs, onFrame: (...args: any[]) => any, onEncoded: (...args: any[]) => any, onError: (...args: any[]) => any)
  start(): void
  stop(): void
  getStats(): CaptureStatsJs
  requestKeyframe(): void
  setBitrate(bps: number): void
}
export declare class AudioSession {
  constructor(opts: AudioOptionsJs, onChunk: (...args: any[]) => any, onError: (...args: any[]) => any)
  start(): void
  stop(): void
  getStats(): AudioStatsJs
}
