/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AudioOptionsJs {
  mode: string
  pid?: number
  includeTree?: boolean
}
export interface AudioStatsJs {
  deliveredChunks: bigint
  droppedChunks: bigint
  discontinuities: bigint
}
export declare function version(): string
export declare class AudioSession {
  constructor(opts: AudioOptionsJs, onChunk: (...args: any[]) => any, onError: (...args: any[]) => any)
  start(): void
  stop(): void
  getStats(): AudioStatsJs
}
